apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  # Обратите внимание на namespace – он должен быть argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    # Указываем путь до чарта
    path: charts/argocd-image-updater
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - secrets+age-import:///helm-secrets-private-keys/key.txt?../../values/argocd-image-updater.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
