kind: SecurityGroup
apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
metadata:
  name: prod-security-group
spec:
  forProvider:
    name: prod
    folderIdRef:
      name: default
    networkIdRef:
      name: default
    ingress:
      - description: rule-https
        protocol: tcp
        port: 443
        v4CidrBlocks:
          - 0.0.0.0/0
      - description: rule-internal-traffic
        protocol: any
        fromPort: 0
        toPort: 65535
        predefinedTarget: self_security_group
      - description: rule-internal-k8s-pods-services
        protocol: any
        fromPort: 0
        toPort: 65535
        v4CidrBlocks:
          - 10.97.0.0/16
          - 10.113.0.0/16
      - description: rule-yc-balancing
        protocol: tcp
        fromPort: 0
        toPort: 65535
        v4CidrBlocks:
          - 198.18.235.0/24
          - 198.18.248.0/24
      - description: rule-icmp-internal
        protocol: icmp
        v4CidrBlocks:
          - 10.0.0.0/8
          - 192.168.0.0/16
          - 172.16.0.0/12
    egress:
      - description: rule-egress-all
        protocol: any
        fromPort: 0
        toPort: 65535
        v4CidrBlocks:
          - 0.0.0.0/0
---
kind: SecurityGroup
apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
metadata:
  name: dev-security-group
spec:
  forProvider:
    name: dev
    folderIdRef:
      name: default
    networkIdRef:
      name: default
    ingress:
      - description: rule-https
        protocol: tcp
        port: 443
        v4CidrBlocks:
          - 0.0.0.0/0
      - description: rule-internal-traffic
        protocol: any
        fromPort: 0
        toPort: 65535
        predefinedTarget: self_security_group
      - description: rule-internal-k8s-pods-services
        protocol: any
        fromPort: 0
        toPort: 65535
        v4CidrBlocks:
          - 10.98.0.0/16
          - 10.114.0.0/16
      - description: rule-yc-balancing
        protocol: tcp
        fromPort: 0
        toPort: 65535
        v4CidrBlocks:
          - 198.18.235.0/24
          - 198.18.248.0/24
      - description: rule-icmp-internal
        protocol: icmp
        v4CidrBlocks:
          - 10.0.0.0/8
          - 192.168.0.0/16
          - 172.16.0.0/12
    egress:
      - description: rule-egress-all
        protocol: any
        fromPort: 0
        toPort: 65535
        v4CidrBlocks:
          - 0.0.0.0/0
